### ISSUE TITLE
Android Intermediate Courses to be Completed

### ISSUE THREAD

**Issue by megGill** [megGill/Treehouse#2]
## TODO

*Courses left to complete in the Treehouse Android Intermediate Track*

* [ ] Styles and Themes in Android
* [ ] Dependency Management with Grade
* [ ] Android Activity Lifecycle
* [ ] Android Permissions
* [ ] Android Fragments
* [ ] Google Play Services
* [ ] Data Persistence with Room

:tada: 🙆‍♀️ 🎊

**Comment by megGill** [comment]
> Courses left

**Comment by megGill** [comment]
:neckbeard:

**Comment by megGill** [comment]
:feelsgood:
